services:
  caddy:
    build: .
    image: caddy-inwx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - INWX_USERNAME=${INWX_USERNAME}
      - INWX_PASSWORD=${INWX_PASSWORD}
    networks:
      - proxy

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy:
    external: true
