services:
  caddy:
    build: .
    image: caddy-hetzner:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - HETZNER_DNS_TOKEN=${HETZNER_DNS_TOKEN}

volumes:
  caddy_data:
  caddy_config:
